### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by nata-pavliuk** [kevmo314/browser-geo-tz#9] opened 2024-11-29 13:25 UTC
Hi, @kevmo314 I still have an issue. I can identify the correct function in the codebase.
But have an issue in the browser

<img width="695" alt="Screenshot 2024-11-28 at 14 49 01" src="https://github.com/user-attachments/assets/9f33d88e-4cb2-4049-a618-268bcd8adfe5">
<img width="635" alt="Screenshot 2024-11-28 at 14 46 27" src="https://github.com/user-attachments/assets/8ec01b0b-e054-452c-a513-cf9139d8031f">

**Comment by kevmo314** [comment] 2024-11-29 18:59
Could you try https://github.com/kevmo314/browser-geo-tz/commit/bb3c58f02b57ca5079a44156226598442ea9b389 released in 0.1.2? If it does not work, can you provide more concrete steps to reproduction? That commit works for me in building a typescript project.

**Comment by r-r-lima** [comment] 2024-12-03 11:21
Hi, I'm having a similar issue, in my case during build/resolve. Replicated using the latest version provided by that commit you mentioned.
Using vite v5.4.11

Failed to resolve entry for package "browser-geo-tz". The package may have incorrect main/module/exports specified in its package.json. [plugin vite:dep-scan]

**Comment by r-r-lima** [comment] 2024-12-03 14:01
In the end I went and imported "find" directly from browser-geo-tz/src/find:
`import { find } from "browser-geo-tz/src/find";`
That way vite managed to resolve and runs fine in the browser.
Maybe it got confused since the package doesn't ship with an "index.js", dunno.
Anyway I hope this helps.

**Comment by kevmo314** [comment] 2024-12-16 16:25
![image](https://github.com/user-attachments/assets/50741d34-25cc-4df3-9e9d-74be9e1af6c4)

![image](https://github.com/user-attachments/assets/2229b87c-ae9f-407e-bd95-c57a30158bb6)

I pushed another patch which seems to fix this in my vite build. The workaround that @r-r-lima mentioned does work as well though.

**Closed as completed** 2024-12-16 16:26 UTC
